enhance bin/check, rubocop

diff --git a/bin/check b/bin/check
--- a/bin/check
+++ b/bin/check
@@ -38,13 +38,13 @@ if [ $? -eq 0 ]; then
   exit 1
 fi
 
-#bundle exec rubocop -D -c .rubocop.yml --fail-fast
-#if [ ! $? -eq 0 ]; then
-#  echo 'rubocop detected issues!'
-#  bundle exec rubocop -a -D -c .rubocop.yml
-#  echo 'Tried to auto correct the issues, but must be reviewed manually, commit aborted'
-#  exit 1
-#fi
+bundle exec rubocop -D -c .rubocop.yml --fail-fast
+if [ ! $? -eq 0 ]; then
+  echo 'rubocop detected issues!'
+  bundle exec rubocop -a -D -c .rubocop.yml
+  echo 'Tried to auto correct the issues, but must be reviewed manually, commit aborted'
+  exit 1
+fi
 
 scss-lint _sass/**/*.scss
 if [ ! $? -eq 0 ]; then
