enhance bin/check, describe bin/check better

diff --git a/bin/check b/bin/check
--- a/bin/check
+++ b/bin/check
@@ -87,3 +87,11 @@ if [ $? -eq 0 ]; then
   echo 'Found a warning in stdout, aborting commit'
   exit 1
 fi
+
+grep -i 'error' tmp/out.log
+if [ $? -eq 0 ]; then
+  cat tmp/out.log
+  echo '----'
+  echo 'Found an error in stdout, aborting commit'
+  exit 1
+fi
