ensure that no mistakes will happen

diff --git a/bin/check b/bin/check
--- a/bin/check
+++ b/bin/check
@@ -44,6 +44,12 @@ if [ $? -eq 0 ]; then
   exit 1
 fi
 
+grep -i -r '_blank' src/documents src/helpers src/layouts --exclude-dir="src/documents/scripts"
+if [ $? -eq 0 ]; then
+  echo '_blank found. Remove it, this is done automatically. Commit aborted'
+  exit 1
+fi
+
 mdl .
 if [ ! $? -eq 0 ]; then
   echo 'Violated markdown rules, see https://github.com/mivok/markdownlint/blob/master/docs/RULES.md, commit aborted'
